### PR TITLE
Implement SDL-0243 Manager Update for Display Capability

### LINKED ISSUE #1386: [SDL 0243] Manager Update for DisplayCapability
Proposal: [Manager Update for DisplayCapability](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0243-manager-update-display-capability.md)

> This proposal adds display capabilities redesign described in [SDL 0216 Widget Support](0216-widget-support.md) (see issue [#664](https://github.com/smartdevicelink/sdl_evolution/issues/664)) to SystemCapabilityManager.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/797

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revisions:
- In addition to`- (nullable SDLWindowCapability *)windowWithID:(NSNumber<SDLInt> *)windowID; `, include `- (nullable SDLWindowCapability *)mainDisplayMainWindowCapabilities;` with property ` defaultMainWindowCapability`
- Change “In order to avoid clashes with the mobile API the enum should not be extended any further without adding the enum values to the mobile API.” to “In order to avoid clashes with the mobile API the enum should only be extended with extreme caution when absolutely necessary or by adding the enum values to the RPC Spec.”

> The proposal .md file was updated to reflect these revisions on 8/22/19.

### PR DESCRIPTION
**Pull request by yLeonid**
Fixes #1386

Update from #1390 

This PR is **ready** for review.

### Risk

This PR makes minor API changes.

### Testing Plan

Extend unit tests to confirm display capability/capabilities conversion is as expected.

### Summary

This PR changes SystemCapabilityManager according to SDL-0243 to make new capabilities available and also convert DisplayCapability and DisplayCapabilities objects.

### Changelog

Existing SystemCapabilityTypes are marked as deprecated hence will appear as deprecated if apps are using them.

### Enhancements

* Adds new capability to the manager
* Adds conversion of display capability objects for developer's convenience

### Tasks Remaining:

- [x] Add DISPLAYS to manager
- [x] Add Conversion code
- [x] Do the unit (UI) tests

- [x] [Wait for #1350 to be merged before requesting review]

### CLA

- [x] I have signed the CLA

### CODE REVIEW

**Comment by theresalech** [comment]
@yLeonid @kshala-ford can you please confirm if this is ready for Livio review?  It appears there are still some tasks remaining.  Note that this remaining task `[Wait for #1350 to be merged before requesting review]` is complete, as PR #1350 was merged on September 3, 2019.

**Comment by yLeonid** [comment]
@theresalech I need to double check the PR #1350 and then I confirm if it is ready

**Comment by yLeonid** [comment]
@theresalech This changeset build upon the PR #1350 so it contains  everything from that PR.

**Comment by joeljfischer** [comment]
@yLeonid I will review this PR today. Due to time constraints if there are any needed fixes I will open a new PR with those fixes and have another Livio developer review. Thank you for your work thus far.

**Comment by yLeonid** [comment]
@joeljfischer  Thank you Joel.

**Comment by joeljfischer** [comment]
Closed in favor of #1427

**Pull request closed without merging**
