### PR TITLE
Implement SDL 0105 Remote Control - Seat

### LINKED ISSUE #792: [SDL 0105] Remote Control - Seat
Proposal: [Remote Control - Seat](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0105-remote-control-seat.md)

> This proposal allows mobile applications to control powered seats within a vehicle (while the vehicle is in parking). A mobile application can send a remote control command to adjust seat positions, turn on or off cooled/heated seat, or change massage settings. The application can also get the status of each seat as well as receive notifications once the status of any seat changes.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/314

### PR DESCRIPTION
**Pull request by mrapitis**
Fixes #792 

This PR is **ready** for review.

## Risk

This PR makes **minor** API changes.

## Testing Plan

Added new unit tests and expanded existing ones

## Summary

Added RPC's, structs, enums as defined in the Remote Control - Seat proposal.

## CLA

- [x] I have signed the CLA

### CODE REVIEW

**Comment by joeljfischer** [comment]
Note that because this has not been marked for release in Core, the date that this would be pulled in is currently undetermined.

**Comment by mrapitis** [comment]
@joeljfischer PR has been updated to align with current develop.  Please review when time permits, core changes are planned for the 5.0 release and have been merged into develop as can be seen here https://github.com/smartdevicelink/sdl_core/issues/1860

**Comment by mrapitis** [comment]
@theresalech this PR is ready for review.  Thanks!

**Comment by mrapitis** [comment]
@joeljfischer please re-review when time permits.  Thanks!

**Pull request merged**
