### PR TITLE
Fix implicit captures of self

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes improperly creating strongSelf variables within blocks and inadvertantly capturing self

### CODE REVIEW

**Comment by asm09fsu** [comment]
@joeljfischer shouldn't a check of strongSelf be done after dancing from weak to strong, as a safety check?

**Comment by joeljfischer** [comment]
@asm09fsu No, because it's the first thing done within the block and the block itself would be released if `self` had been released. So it's running the block from self, then strongifying the weak self which will exist. Does that make sense?

**Comment by asm09fsu** [comment]
@joeljfischer I agree, I just usually see it done this way, wasn't sure if added the extra check (or not, would help or hinder us).

**Comment by joeljfischer** [comment]
@asm09fsu Yeah, it's a good question, but I don't think the added check would help us.

**Pull request merged**
