### PR TITLE
Fix apps running iOS 13 multi-window not working correctly with the lock screen

### LINKED ISSUE #1430: Index 0 beyond bounds for empty array crashes in SDL library (6.3.1)
### Bug Report
My project got two crashes from SDL library (iOS).
The number line are difference, but the root cause are same.
And it only happens on the **iOS 13+.**

*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array
SDLScreenshotViewController.m line 37
SDLScreenshotViewController.m line 50

I leave some screen shots on the slack.
[https://smartdevicelink.slack.com/archives/C0K32T48Y/p1569995789023500](https://smartdevicelink.slack.com/archives/C0K32T48Y/p1569995789023500)

##### Reproduction Steps
1. Launch the app
2. Wait a moment (2 min)
3. Crash(Random)

##### Expected Behavior
Not crash

##### OS & Version Information
* iOS Version: 13.1+
* SDL iOS Version: 6.3.1
* Test Mobile: iPhone X, iPhone MS MAX 
* XCode: 11.0

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #1430, #1469 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
1. Unit tests were run.
2. The Swift example app was updated to run iOS 13 multi-window scene API and smoke tested.
3. A separate example app supporting rotation was built on the iOS 13 multi-window scene API and smoke tested.
4. The Obj-C example app continues to support the old-style windowing system and smoke tested.

### Summary
This PR makes a few changes to lock screen support especially relating to iOS 13.

1. There was a crash accessing `[UIApplication sharedApplication].windows[0]` on iOS 13.
2. Lock screens on iOS 13 often failed to work properly; they would appear as a black screen without animation.
3. Rotation did not work correctly when the presenting root VC supported rotation.

##### Bug Fixes
* Fixed several bugs relating to iOS 13 scene-based windowing support (multi-window) including a crash, rotation issues, and failures to show the lock screen.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by NicoleYarroch** [comment]
I found an iOS 13 issue with dismissing the lockscreen when the phone is disconnected while the app is in the background. This is not an issue with iOS 12 dismissal code

1. Connect the SDL_iOS Swift example app to the head unit while the app is open on the phone. Trigger a `DD_ON` notification so the car is moving and the lock screen shows on the phone. 
1. Put app on phone in the background
1. Pull the USB cord
1. Bring app on phone to the foreground

**Expected Result**
The lock screen should be dismissed.

**Actual Result**
The lock screen is not dismissed.

**Comment by joeljfischer** [comment]
@NicoleYarroch Fixed

**Comment by NicoleYarroch** [comment]
The only issue I noticed is that now that the lockscreen supports landscape mode, the layout of the icons obscures the Lock Screen Dismissal Warning. 
Landscape - Dismissal Warning

**Comment by joeljfischer** [comment]
@NicoleYarroch fixed

**Comment by SatbirTanda** [comment]
Have not been able to reproduce the original crash, but can confirm I do not see any broken behavior with the changes. One small detail - a
ttached is a video and from 0:15-0:20 you can see that the lock screen presents itself and the sort of disappears (originally, It would slide back down).
[RPReplay_Final1573691903.MP4.zip](https://github.com/smartdevicelink/sdl_ios/files/3844146/RPReplay_Final1573691903.MP4.zip)

**Comment by joeljfischer** [comment]
Hi Satbir, I saw the video, but it's difficult to discern exactly what is happening. Can you give us additional information on which module / version you were testing against as well as what you were doing when that jitter occurred (e.g. was it when you plugged the device in, or when you were changing the driver distraction state, etc.).

**Comment by SatbirTanda** [comment]
Hey Joel,
From 0:15-0-20 was on connection to SYNC (18025), and then launching the app from sync with speed set to 0.  Later in the video is me toggling between speed = 100 and speed = 0.

**Comment by joeljfischer** [comment]
I believe that may be related to a particular version of Sync. I'm not seeing the behavior on newer versions of Sync nor with Manticore running Core 5.1.0.

**Pull request merged**
