### PR TITLE
SDL0285: ShowConstantTBT Description Update

### LINKED ISSUE #1863: [SDL 0285] ShowConstantTBT Description Update
Proposal: [ShowConstantTBT Description Update](https://github.com/smartdevicelink/sdl_evolution/edit/master/proposals/0285-ConstantTBT-Update.md)

> This proposal is to update the descriptions of `ShowConstantTBT`'s parameters `distanceToManeuver` and `distanceToManeuverScale` so we get consistent use of them across all OEMs and Navigation apps.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/955

The following comments need to be updated: 
- `ShowConstantTBT.distanceToManeuver`
- `ShowConstantTBT.distanceToManeuverScale`

### PR DESCRIPTION
**Pull request by yoooriii**
Fixes #1863 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
No tests performed since this pull request does not update existing codebase but commented text alone

#### Core Tests
No tests performed since this pull request does not update existing codebase but commented text alone

### Summary
The descriptions (comments) for 2 fields 'distanceToManeuver' and 'distanceToManeuverScale' are updated.

##### Breaking Changes
* no breaking changes

##### Enhancements
* no enhancements

##### Bug Fixes
* no bug fixes

### Tasks Remaining:
- [x] none

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by perryneal11 — APPROVED** [review]

**Comment by perryneal11** [comment]
@yoooriii running the unit tests is still required as well as running against core (or explaining why not applicable). Could you please complete final two check boxes?

**Comment by yoooriii** [comment]
> running



> Could you please complete final two check boxes?

Done

**Comment by yoooriii** [comment]
The test SDLVoiceCommandManagerSpec has nothing to do with this PR though it is failing.

**Comment by a-prykho** [comment]
Hi @jordynmackool , @joeljfischer this PR is ready for Livio review.

**Comment by perryneal11** [comment]
@theresalech This is approved by ford

**Review by NicoleYarroch — APPROVED** [review]

**Pull request merged**
