### PR TITLE
Feature/haptic manager

### PR DESCRIPTION
**Pull request by ChrisB-Elektrobit**
This PR addresses the following issues:
•	https://github.com/smartdevicelink/sdl_ios/issues/698
•	https://github.com/smartdevicelink/sdl_ios/issues/728

This PR is **[ready]** for review.

### Notes

Alternative implementations for the viewForSDLTouch() function were considered.
The current approach was considered more readable.  Pending code review feedback.

### Risk
This PR makes **[no]** API changes. (No changes to MOBILE_API.xml or HMI_API.xml, changes were contained within the iOS proxy layer)

### Testing Plan
Testing was mainly done through a modified Example app that is already provided as a part of the sdl_ios repository.  From that test application, an instance of "HapticManager" was created with a UI view window provided as a parameter.  We observed that the "HapticManager" was able to successfully extract the geometry of focusable elements and use these while triggering a call to SendHapticData RPC.  In our test setup, we were able to see the SendHapticData RPC being received by a simulated head unit with the proper parameters as extracted by the "HapticManager".  In addition, the "HapticManager"'s viewForSDLTouch() function was fed with a number of (x,y) coordinates to test the second use case as described above.  We tested points both inside and outside of the various rectangles in order to confirm that the appropriate UI views were either selected or remained unselected.

### Summary

The changes included in this pull request are intended to provide a convenience layer for mobile apps running on iOS that would like to use haptic input via the SendHapticData RPC.  The main use case provided the capability to scan a provided view for focusable elements and extract the view's geometry.
The extracted geometry is then passed on to the SendHapticData RPC. Additionally, a use case is supported where based on provided x,y coordinates, a search is performed for a UI element that would contain the provided x,y coordinates within its geometry. Both use cases are implemented as part of a new class called the "HapticManager".

##### Breaking Changes
* No breaking changes

##### Enhancements
* A new class "HapticManager" was implemented. Because of ongoing discussions as to where to call the functionality from, no further integration was done.  The decision on the final integration point will be up to the project maintainers.

##### Bug Fixes
* No bug fixes

### Tasks Remaining:
- No tasks remaining

### CLA
- [ x ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by ChrisB-Elektrobit** [comment]
We removed the unnecessary example app code changes from our branch, the code should now be ready for merge (pending review comments).  Thanks!

**Comment by joeljfischer** [comment]
Hi @ChrisB-Elektrobit, I've only gotten a little into the code, but your PR needs cleanup as well. Please follow the format of other PRs for naming the PR itself (it helps with searching later), see #729 or #692 for examples of naming.

Second, you altered the text at the top saying what issues it fixes. Please stick to the template, as github has automated features for closing issues when PRs say "Fixes #issue" etc.

The Risk is also incorrect. The risk is about API changes within the library, not the mobile XML or HMI XML.

Please use standard markdown features such as code highlighting using backticks `` to delinate things that are names of functions or classes. This makes paragraphs describing code much more readable. There are a few examples of this in #721.

It would be helpful in your changelog to specify which SDL proposals each change makes, for an example of this, please see #721. This will help in writing the changelog in the future.

A very minor thing, but please fix your CLA checkbox. To be formatted correctly, it needs to be `[x]`

All mostly minor stuff, but it helps when looking through these to write changelogs, and for future documentation and searching. I'll provide more detailed code review in the near future.

**Comment by joeljfischer** [comment]
This PR has not been built against the `release/5.0.0` branch, and does not contain any unit tests, unit tests are a requirement of all added features, as noted in the contribution guides. So:

* Change target branch to `release/5.0.0`
* Add unit tests
* Update PR title and text as noted in the above comment.

**Comment by ChrisB-Elektrobit** [comment]
Hi Joel,
We created a new pull request to address your comments: https://github.com/smartdevicelink/sdl_ios/pull/751
Unit tests will be added tomorrow.
Thanks!

**Comment by joeljfischer** [comment]
Closed in favor of #751

**Pull request closed without merging**
