### PR TITLE
fix to stop audio streaming at HMI level none and background

### LINKED ISSUE #803: Audio stream is not stopped at hmi level none and background
### Bug Report
Audio stream is not stopped when hmi level are changed to none or background from limited or full.
According to this guide, audio streaming is only allowed at hmi level limited and full.
https://smartdevicelink.com/en/guides/iOS/mobile-navigation/audio-streaming/

##### Reproduction Steps
1. Start SDL app (appHMIType = Navigation) and connect to SDL core
2. Change HMI level to full
3. Change HMI level to background or none

##### Expected Behavior
Audio streaming and video streaming are stopped 

##### Observed Behavior
Audio streaming is not stopped. Only video streaming is stopped.

##### OS & Version Information
* iOS Version: 11.1.2
* SDL iOS Version: 5.0.0-rc3
* Testing Against: Our in-house testing SDL HMI devboard

##### Test Case, Sample Code, and / or Example App
PR will be created.

### PR DESCRIPTION
**Pull request by t-yoshii**
Fixes #803 

This PR is ready for review.

### Risk
This PR makes no API changes.

### Testing Plan
This PR also fixes unit test in SDLStreamingMediaLifecycleManagerSpec.m.

### Summary
Currently isHmiStateAudioStreamCapable() in SDLStreamingMediaLifecycleManager.m always return YES. This fix changes this function to return YES only when HMI level is limited or full same as isHmiStateVideoStreamCapable()

According to this guide, audio streaming is only allowed at hmi level limited and full.
https://smartdevicelink.com/en/guides/iOS/mobile-navigation/audio-streaming/

##### Bug Fixes
* Fix to stop audio streaming when HMI level changes to none or background from limited or full.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by joeljfischer** [comment]
@t-yoshii This was automatically closed when I removed the `release/5.0.0` branch. As this is a bugfix, it would be targeted to master.

**Comment by joeljfischer** [comment]
I'm also fairly certain that Audio Streaming works in the BACKGROUND HMI type as well.

**Comment by t-yoshii** [comment]
Hi @joeljfischer ,Thanks for the review.
I noticed that HMI state diagram is removed from latest Audio Streaming guide...
https://smartdevicelink.com/en/guides/iOS/mobile-navigation/audio-streaming/
I understand Audio Streaming is now allowed even in background.

I have one question. Should app check the audio streaming state (AUDIBLE, NOT_AUDIBLE, ATTENUATED) before sending audio streaming data?

**Comment by joeljfischer** [comment]
No, a Navigation app does not need to do that as their audio is time sensitive and other audio will be attenuated to them. Navigation apps are the only ones using this system.

**Pull request closed without merging**
