### PR TITLE
Streaming Putfile enhancement

### PR DESCRIPTION
**Pull request by adein**
Changes for PutFile to allow streaming similar to Android.

Issue #271

### CODE REVIEW

**Comment by joeljfischer** [comment]
This is a pretty big change, any chance we can push it to 4.1?

Couple of issues I see:

1. Based on develop from June 2. This will need to be updated by merging in the target branch to this branch. A lot seems to have changed, so this might be a headache (sorry!).
1. It would be nice if it followed the style guide, but I think we said we weren't going to enforce it until post 4.0.0, so no worries if it can't happen.
1. It would be really nice to have tests, but since that class doesn't have any tests built yet and that's a major project, I certainly wouldn't expect them unless we pushed the release back.

I haven't yet tested or thoroughly reviewed the code.

**Comment by adein** [comment]
I'm not sure about 4.0 vs 4.1.  @Heath-FoMoCo - does this need to be 4.0?

**Comment by adein** [comment]
@joeljfischer Yes, this can be delayed to 4.1.

**Comment by joeljfischer** [comment]
:+1:

**Pull request closed without merging**
