### PR TITLE
Fix for using NS_TYPED_ENUM instead of SDL_SWIFT_ENUM

### LINKED ISSUE #1834: Generator should generate enums with NS_TYPED_ENUM instead of SDL_SWIFT_ENUM
### Bug Report
In the last release we removed the need for the SDL_SWIFT_ENUM workaround. It should be removed from the generator.

### PR DESCRIPTION
**Pull request by FrankElias77**
Fixes #1834 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Replace SDL_SWIFT_ENUM with NS_TYPED_ENUM.

##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Replace SDL_SWIFT_ENUM with NS_TYPED_ENUM.

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by joeljfischer — CHANGES_REQUESTED** [review]
Unit tests are failing

**Comment by FrankElias77** [comment]
> Unit tests are failing

Which tests specifically? the unit tests in xcode have passed and ci tests have passed too

**Comment by joeljfischer** [comment]
> > Unit tests are failing
> 
> 
> 
> Which tests specifically? the unit tests in xcode have passed and ci tests have passed too

The Python tests. The CI doesn't have them on this branch.

**Comment by FrankElias77** [comment]
> > > Unit tests are failing
> > 
> > 
> > Which tests specifically? the unit tests in xcode have passed and ci tests have passed too
> 
> The Python tests. The CI doesn't have them on this branch.

These errors are related to the missing 'history' param which are handled #1844 , did not notice an error related to the changes made in this PR

**Pull request merged**
