### PR TITLE
[WIP] ALM for iOS

### PR DESCRIPTION
**Pull request by kmilitel**
Summary

Automated Lifecycle Management (ALM) is currently used in SDL-Android to handle lifecycle events of the proxy for the developer. An example is Bluetooth disconnects. Another is that SDLProxyALM, a subclass of SDLProxyBase, will automatically send a RegisterAppInterface RPC at the appropriate time. This process simplifies the work a developer needs to do by moving some of the leg work into the SDK itself.

This pull request is an initial preview (work in progress) of ALM for iOS. This primarily involves replacing SDLProxy with a base class and a ALM wrapper class. Other initiatives have been started such as sessions and connection management.

#### General

  - [ ] Ensure SDLProxyALM & SDLProxyBase class meets the goals of ALM.
  - [ ] Determine what translations from sdl_android are not valid.
  - [ ] Other classes were created when translating ALM from Android to iOS implementation. These other classes may not be implemented.
  - [ ] Properly log and handle errors

### CODE REVIEW

**Comment by joeljfischer** [comment]
Can you add what ALM is and what the purpose behind it is?

**Comment by kmilitel** [comment]
I have updated the summary to include a description of ALM, and how it is currently used in the SDL Android SDK.

**Comment by Heath-FoMoCo** [comment]
This is ready to start testing and merging in a development stream to make a reality.  Can we get this on the agenda for our next review?

**Comment by joeljfischer** [comment]
Before we do, can your team create a presentation for this PR, and / or make the PR's summary more filled out like #99, explaining the goals and some detail about the execution? There are a dozen or two new files, and a large rearchitecture. I think I understand the basic purpose, but I would like to know the philosophy behind it, how the classes relate, etc.

In addition, there have been many changes to the library since this was first proposed, and will have to have the develop branch merged in when 4.0 goes final to bring it up to date. This is also definitely a major version change, so it can be slated for 5.0 or 6.0.

What is still work in progress on this branch?

**Comment by joeljfischer** [comment]
Closed for #255

**Pull request closed without merging**
