### PR TITLE
Feature/alm

### PR DESCRIPTION
**Pull request by kmilitel**
**Summary**

This pull request is an initial preview of ALM for iOS, ready for review. This primarily involves replacing SDLProxy with a base class and a ALM wrapper class. Other initiatives have been started such as sessions and connection management. There are are methods that may need to be implemented

ALM is also a pre-requisite for adding Cordova integration.

**TODO**

* Ensure SDLProxyALM & SDLProxyBase class meets the goals of ALM.
* Assess iAPTransport delegate implementation.
* Determine what translations from sdl_android are not valid.
* Other classes were created when translating ALM from Android to iOS implementation. These other classes may not be implemented.
* Properly log and handle errors

### CODE REVIEW

**Comment by joeljfischer** [comment]
Can #169 be closed?

**Comment by kmilitel** [comment]
Yes #169 can be closed.

**Comment by joeljfischer** [comment]
@adein @Heath-FoMoCo Has this been superseded by #298?

**Comment by adein** [comment]
@joeljfischer While technically separate, #298 would pretty much supersede this one because developers would be working with the new abstraction instead of directly with the proxy.  However, part of #255 was to align the Android and iOS SDKs to facilitate a Cordova implementation.

**Comment by joeljfischer** [comment]
@adein Soooo.....can I close it? :smile_cat:

**Comment by Heath-FoMoCo** [comment]
Yes.  You can close it.

**Pull request closed without merging**
