### PR TITLE
Implement SDL 0072 New vehicle data - FuelRange

### LINKED ISSUE #641: [SDL 0072] New vehicle data - FuelRange
Proposal: [New vehicle data - FuelRange](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0072-New-vehicle-data-FuelRange.md)

> This proposal is about adding a new vehicle data to get the distance a vehicle can travel with the current level of fuel.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/207

Steering Committee Decision:

> The Steering Committee has voted to accept this proposal with revisions. It was agreed that FuelType and range be optional and not mandatory, based on the reasons provided in the comments on the issue.  These revisions have now been made to the referenced proposal .md file.

### PR DESCRIPTION
**Pull request by mrapitis**
Fixes #641 

This PR is **ready** for review.

## Risk

This PR makes **minor** API changes.

## Testing Plan

Added new unit tests and expanded existing ones

## Summary

Added Vehicle Data RPC's, structs, enums as defined in the fuel range proposal.

## CLA

- [x] I have signed the CLA

### CODE REVIEW

**Comment by joeljfischer** [comment]
@mrapitis This hasn't been scheduled for Core v4.4, so this won't be merged for probably 6 months and a lot can change between now and then. Do you want to keep this open until then?

**Comment by mrapitis** [comment]
@joeljfischer Would it be possible to review / merge the proxy side changes prior to the core implementation?

**Comment by joeygrover** [comment]
@mrapitis unfortunately, no. We are no longer merging in RPC additions on whims. We are merging them in based on RPC spec versions. This makes it much clearer which version of the proxy support which version of the RPC spec. The next RPC spec will need to be approved with that addition before it gets merged into the proxy.

**Comment by mrapitis** [comment]
@joeygrover Understood, I'll close for now and resubmit when we have an approved version.

**Pull request closed without merging**
