### PR TITLE
Implement SDL-0221 Remote Control - Allow Multiple Modules per Module Type  

### LINKED ISSUE #1272: [SDL 0221] Remote Control - Allow Multiple Modules per Module Type
Proposal: [Remote Control - Allow Multiple Modules per Module Type](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0221-multiple-modules.md)

> SDL remote control baseline proposal [SDL-0071](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0071-remote-control-baseline.md) groups available controllable items of the same category into a RC module type. SDL defines six module types: `RADIO`, `CLIMATE`, `AUDIO`, `LIGHT`, `HMI_SETTINGS` and `SEAT`. SDL allows only one module per module type so far. However, there are production needs to support multiple modules of the same module type. For example, some vehicles in the market are equipped with "dual-zone" climate control systems. There are also ["tri-zone" or even "quad-zone" climate control](https://www.autotrader.com/car-info/definitions-dual-zone-climate-control-211783) in the existing vehicles. Some vehicles in the market have seat control for several seats (driver's seat, front passenger's seat for example). Some vehicles have both a default entertainment system and a back seat entertainment system. There are car headrest monitors, seat back monitors, car roof mount monitors and flip down screens. Passengers can use a back seat entertainment system to play video, audio or even games.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/700

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revisions:

- The default `userLocation` should be DRIVER to ensure backwards compatibility
- Add new non-mandatory `userLocation` parameter to `SetGlobalProperties` RPC instead of including `userLocation` as a parameter in each Remote Control request, such as `GetInteriorVehicleDataConsent`, SetInteriorVehicleData`, etc.

> The proposal .md file was updated to reflect these revisions on 5/21/19.

### PR DESCRIPTION
**Pull request by SatbirTanda**
Fixes #1272 

This PR is ready for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
Added Unit Tests

### Summary
Create 2 new RPCs (GetInteriorVehicleDataConsent & ReleaseInteriorVehicleDataModule) and add moduleId and moduleType param to existing classes. Deprecate SDLSeatLocation and a few initializers.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by theresalech** [comment]
@SatbirTanda as there is a currently an Evolution Proposal in review regarding this feature ([here](https://github.com/smartdevicelink/sdl_evolution/issues/791)), we will need to wait for that proposal to be voted on by the SDLC Steering Committee before reviewing this PR. The vote is scheduled to take place 2019-07-30.

**Comment by SatbirTanda** [comment]
@theresalech ready for review

**Comment by SatbirTanda** [comment]
@theresalech ready for review.  this PR was tested against the `origin/feature/multiple_modules` branch of sdl_core running in docker container and sdl_hmi running in google chrome.  on iOS this branch of SDL was used + the example app in the library to make requests.

**Comment by SatbirTanda** [comment]
@theresalech ready for rearview

**Comment by SatbirTanda** [comment]
@theresalech ready for review

**Comment by AStasiuk** [comment]
@justingluck93, there are no opened issues in core right now. Could you please specify about which issues are talking about?

**Comment by justingluck93** [comment]
The issues is with an open PR https://github.com/smartdevicelink/sdl_core/pull/2984 not anything currently in core. It deals with getting consent to control a module.

**Comment by AStasiuk** [comment]
@justingluck93 , could you please specify preconditions, steps for reproduction and SDL logs.
Suggested to put all this info in https://github.com/smartdevicelink/sdl_core/pull/2984

**Comment by IGapchuk** [comment]
@SatbirTanda Please be informed, that `SDL Core`'s behavior has been changed during `SDL Core`'s changes review. Please take a look at the following comments:

- https://github.com/smartdevicelink/sdl_core/pull/2984#issuecomment-526566099
- https://github.com/smartdevicelink/sdl_core/pull/2984#issuecomment-526681314
- https://github.com/smartdevicelink/sdl_core/pull/2984#issuecomment-526717067

that describe the new behavior for `getting consent to control a module` for all `accessMode` flows:

```
1. If accessMode=AUTO_ALLOW, return true by default
2. If accessMode=AUTO_DENY, check if another app is using the resource
   a. If the resource is IN_USE, return false
   b. If the resource is FREE, return true
3. If accessMode=ASK_DRIVER, check if the consent is cached
 a. If it is cached, return that result
 b. If it is NOT cached, check if another app is using the resource
    i) If the resource is FREE(and the user in the resource’s serviceArea), return true
    ii) If the resource is IN_USE, prompt the driver for consent 
   b. If it is NOT cached, then prompt the driver for consent
```
Also in these comments, you can find references to commits with appropriate changes in `SDL Core`.
If you will have comments on these changes, please feel free to provide us with them.

**Comment by justingluck93** [comment]
One last thing. I just got information that the Mobile api needs to be changed slightly.

`GetInteriorVehicleDataConsent` response class needs to be updated.

The `allowed` property is now `NOT` mandatory. 

```
<param name=“allowed” type=“Boolean” array=“true” mandatory=“*true*“>
was changed to
<param name=“allowed” type=“Boolean” array=“true” mandatory=“*false*“>
```
Please make this change in all needed places.

**Comment by SatbirTanda** [comment]
@theresalech ready for review

**Pull request merged**
