### PR TITLE
Implement Revisions - SDL 0099 New remote control modules, SDL 0175 Updating DOP value range for GPS notification 

### LINKED ISSUE #1003: [SDL 0175] Updating DOP value range for GPS notification
Proposal: [Updating DOP value range for GPS notification](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0175-Updating-DOP-value-range-for-GPS-notification.md)

> This proposal is to update the range and make these fields non mandatory for DOP values in GPS notification for GetVehicleData and OnVehicleData RPCs.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/510

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions.  The revision will be to include maxValue as described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/510#issuecomment-400474515) from the author.

>The proposal .md was updated on July 2, 2018 to include the agreed upon revisions.

### PR DESCRIPTION
**Pull request by mrapitis**
Fixes #1003, #755 

This PR is **ready** for review.

## Risk

This PR makes **minor** API changes.

## Testing Plan

Added new unit tests and expanded existing ones

## Summary
Updated RPC's, structs, enums as defined in Revise New remote control modules proposal:
https://github.com/smartdevicelink/sdl_evolution/pull/572
&
Updating DOP value range for GPS notification proposal:
https://github.com/smartdevicelink/sdl_evolution/pull/577

For simplicity of review, issues have been combined into single PR as changes are dependent on each other.

## CLA

- [x] I have signed the CLA

### CODE REVIEW

**Comment by mrapitis** [comment]
@joeljfischer we have removed remaining references to GPSLocation.  Please re-review when time permits.  Thanks!

**Comment by mrapitis** [comment]
@joeljfischer we have updated the PR to include latest proposal corrections for https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0099-new-remote-control-modules-and-parameters.md

From:
```
<element name="REAR_LEFT_BREAK_LIGHT" value="16"/>
<element name="REAR_RIGHT_BREAK_LIGHT" value="17"/>
```

To:
```
<element name="REAR_LEFT_BRAKE_LIGHT" value="16"/>
<element name="REAR_RIGHT_BRAKE_LIGHT" value="17"/>
```
Please re-review when time permits.  Thanks!

**Comment by joeljfischer** [comment]
@mrapitis I have a few additional notes:

* `SDLLightControlData` `initWithLightStateArray` -> `initWithLightStates`
* `SDLEqualizerSettings` `initWithChannelId:channelName:channelSetting:` should not exist, as `channelName` is readonly.

**Comment by mrapitis** [comment]
@joeljfischer PR has been updated with provided notes.  Please re-review when time permits. Thanks!

**Pull request merged**
