### PR TITLE
Remove Siphon Server

### PR DESCRIPTION
**Pull request by joeljfischer**
Fixes #57, this removes the siphon server and all associated APIs. See #85 for more information.

### CODE REVIEW

**Comment by Heath-FoMoCo** [comment]
Before we can remove Siphon we have to have an equivalent coded.
Without we would be debugging iOS apps blindly.

**Comment by joeljfischer** [comment]
I understand that, but I was under the impression that SmartDeviceLink apps cannot be debugged through the Siphon Server as it exists, and that this is a Ford only feature.

I'm in total agreement that getting a replacement out there is a top priority, but since this is a major version change, I would say it is better to remove it while we have other major changes batched here, and push for the new system (a minor version change) as soon as possible, whether it be before 4.0 is out or shortly after.

Am I off base here?

**Comment by Heath-FoMoCo** [comment]
It is a Ford feature used to debug partner apps.
When a partner has issues we use this tool to determine if it is app logic or module behavior causing the issue.  Removing this would cripple this support .

**Comment by mikeburke106** [comment]
Pardon my ignorance on the iOS libs, but I believe (in the Android code, at least) if the SiphonServer isn't connected, the logs will just be displayed via LogCat or whatever native log mechanism exists.

From SdlTrace.java:

```java
// Attempt to write formatted message to the Siphon
if (false == writeMessageToSiphonServer(msg)) {
	// If writing to the Siphon fails, write to the native log
	NativeLogTool.logInfo(SdlTrace.SYSTEM_LOG_TAG, msg);
}
```

Is there nothing like this set up in iOS yet, or is this not sufficient for our debugging purposes?

**Comment by Heath-FoMoCo** [comment]
Correct; it is not sufficient.
On Android you can plug into the debugger and get live logging.  This is not possible with iOS plugged into a module.
With iOS you have to do “cable swap” to get logs (module to Mac) and there is always a chance that you will miss the entries.  Painful and not robust enough.

What we need is a way to debug with the cable plugged in the module.   Live code debugging, (Bluetooth, Wi-Fi, magic, anything) with breakpoints, would be awesome.  Right now, we believe, iOS makes this impossible.

**Comment by mikeburke106** [comment]
Ohhhhh ok, I see.  So, the real cause of the problem is that iOS devices can only connect to SDL via USB and it can't write logs to USB at the same time.  I would agree, then, that this can't be removed until we have an alternative implemented.

**Comment by joeljfischer** [comment]
I'm working on a replacement right now, this won't be merged in until that's done. It should be ready for 4.0.

**Pull request closed without merging**
