### PR TITLE
[SDL-0323] Align video streaming parameters with VideoStreamingCapability

### LINKED ISSUE #1860: SDL 0323 - Align video streaming parameters with VideoStreamingCapability
Proposal: [Align video streaming parameters with VideoStreamingCapability](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0323-align-VideoStreamingParameter-with-capability.md)

> When Android SDL application starts video streaming, a developer can specify VideoStreamingParameters, but before actually starting the streaming, those parameters need to be aligned with VideoStreamingCapability returned by head units. The same is true for iOS SDL application; i.e. a developer can specify customVideoEncoderSettings, but those settings need to be aligned with VideoStreamingCapability.

Steering Committee Decision: 
The Steering Committee voted to accept the proposal on 2020-11-24. Xevo, the authoring company of the proposal shared that this proposal's [motivation](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0323-align-VideoStreamingParameter-with-capability.md#motivation) was found while working on the implementation for [SDL 0274](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0274-add-preferred-FPS.md) (an already accepted proposal).
 

Review: https://github.com/smartdevicelink/sdl_evolution/issues/1094

### PR DESCRIPTION
**Pull request by shiniwat**
Fixes #1860

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
This PR has no new Unit Tests

#### Core Tests
sdl_core PR : https://github.com/smartdevicelink/sdl_core/pull/3437

Core version / branch / commit hash / module tested against: https://github.com/smartdevicelink/sdl_core/pull/3437
HMI name / version / branch / commit hash / module tested against: https://github.com/smartdevicelink/sdl_hmi/pull/436

### Summary
This PR has dependency on SDL -274: add preferredFPS to VideoStreamingCapability. Hence this PR is on top of PR at https://github.com/smartdevicelink/sdl_ios/pull/1613.

##### Breaking Changes
* n/a

##### Enhancements
* n/a

##### Bug Fixes
* issue #1860 

### Tasks Remaining:
- n/a

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by jordynmackool** [comment]
@shiniwat please let me know when this PR is ready for Livio Review

**Comment by shiniwat** [comment]
Hi @jordynmackool,
Because this PR is on top of https://github.com/smartdevicelink/sdl_ios/pull/1613 PR, PR for SDL-0274 should be reviewed first, and then this one is ready for review.

**Comment by NicoleYarroch** [comment]
@shiniwat I approved and merged PR #1613 into develop. Can you please merge develop into your branch for this PR and fix the merge conflicts? 

The develop branch has a fix for tests not building on Xcode 12.3 and 12.4 so we no longer have to use a workaround. Just make sure to run `bash carthage-build.sh update --no-use-binaries --platform ios` in the root folder of the library before building the tests. 

Please tag me when you are ready for a review. Thanks!

**Comment by shiniwat** [comment]
Hi @NicoleYarroch, I have merged develop into this PR, made sure running `bash carthage-build.sh update --no-use-binaries --platform ios`, and resolved conflicts at SDLVideoStreamingLifecycleManager.m.
I hope this PR is ready for re-review. Thanks!

**Review by NicoleYarroch — APPROVED** [review]

**Pull request merged**
